### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tredoe** [jmettraux/rufus-tokyo#10]
Hi, I've got the next error when I was adding data to the DB. I'm using the last version downloaded and compiled fom
http://sourceforge.net/projects/tokyocabinet/files/

```
/var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo.rb:48:in `blen': undefined method `size' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:98:in `[]='
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:191:in `block in from_h'
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:191:in `each'
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:191:in `inject'
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:191:in `from_h'
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/util.rb:203:in `[]'
    from /var/lib/gems/1.9.0/gems/rufus-tokyo-0.1.14/lib/rufus/tokyo/cabinet/table.rb:227:in `[]='
    from main.rb:26:in `block in <main>'
    from main.rb:24:in `each'
    from main.rb:24:in `<main>'
```

**Comment by tredoe** [comment]
Well, I'm thinking that the problem could be because I'm storing any values with nil value:

```
{"code3"=>"ALB", "en_name"=>"Albania", "en_remark"=>"", "local_name"=>"", "territory_of"=>nil, "region"=>"EU-S"}
```

**Comment by tredoe** [comment]
I just check it and solve it. The failure was because I was adding data with nil values.
